### ISSUE TITLE
New website content sync helm chart

### ISSUE THREAD

**Issue by hjfbynara** [broadinstitute/bits-helm-charts#2]
Create a new helm chart (content-sync) that copies/syncs/clones a website content using the reposync docker container.  The chart should be implemented using Kubernetes Cron resource type.   The cron/pod should perform the following steps:

1. Run reposync to a mounted Persistent Disk (PD)
2. run any yum repo utility to update PD content to function as a yum repo
3. use gsutil rsync to synchronize content from PD to a google bucket

The PD and google bucket are assumed to be created outside of the helm chart and passed in as a value.   The chart should accept the following values:

- Yum repo URL
- Cron Schedule
- Destination mount path of PD (?)
- google storage bucket name

The chart should only allow a single cron instance running at any one time, keep the last 3 successful and failed iterations so that engineers can easily view logs.

Definition of done:

- a new helm chart
- the ability to helm install the chart to an kubernetes cluster passing the appropriate values
- querying the logs for successful runs show expected results of sync.

NOTE: until nginx helm chart is updated to support running against PDs content validation can wait.

**Comment by daltschu22** [comment]
Created reposync branch which contains helm chart and templates for cron and PD/PV/PVC https://github.com/broadinstitute/bits-helm-charts/compare/main...reposync

**Comment by daltschu22** [comment]
Steps 1, 2, and 3 are finished.
